### ISSUE TITLE
module 'yarl' has no attribute 'quote' error

### ISSUE THREAD

**Issue by despin** [qnnnnez/e-downloader#1]
Trying to run

```pip3 install aiohttp html5lib```
```python
$ python3 main.py --help
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    import download
  File "/home/pedro/Escritorio/e-downloader/download.py", line 20, in <module>
    patch_yarl_quote()
  File "/home/pedro/Escritorio/e-downloader/download.py", line 15, in patch_yarl_quote
    old_quote = yarl.quote
AttributeError: module 'yarl' has no attribute 'quote'
```

**Comment by qnnnnez** [comment]
Fixed. This is a dirty fix for a H@H client written in Go, which doesn't handle URL-encoded URLs properly.
