### ISSUE TITLE
AttributeError: 'Gallery' object has no attribute 'preview_range'

### ISSUE THREAD

**Issue by kontoljanaika** [qnnnnez/e-downloader#2]
help?

**Comment by qnnnnez** [comment]
Please tell me what did you do, and the full stack backtrace.

**Comment by kontoljanaika** [comment]
C:\Users\Danny\edm>main.py download https://e-hentai.org/g/1491980/207c9befe8/

below is the result, sorry, i'm still new in python :"<
C:\Users\Danny\edm>main.py download https://e-hentai(.)org/g/1491980/207c9befe8/
2019-09-29 02:45:14,891 - stream logger added
2019-09-29 02:45:16,881 - Traceback (most recent call last):
  File "C:\Users\Danny\edm\download.py", line 34, in do_forever
    await job()
  File "C:\Users\Danny\edm\download.py", line 58, in get_page
    page = await self.gallery.get_page(self.session, page_id)
  File "C:\Users\Danny\edm\gallery.py", line 113, in get_page
    preview_page = (page - 1) // self.preview_range
AttributeError: 'Gallery' object has no attribute 'preview_range'

**Comment by kontoljanaika** [comment]
nah, it worked.
i forgot to login. XD
