### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text' (doc.find('.//div[@class="gtb"]/p[@class="gpc"]'))

### ISSUE THREAD

**Issue by luckydonald** [qnnnnez/e-downloader#3]
```bash
python main.py download https://e-hentai.org/g/998495/13bba610b4/

Traceback (most recent call last):
  File "main.py", line 112, in <module>
    error_code = main(argv[1:])
  File "main.py", line 53, in main
    loop.run_until_complete(run())
  File "/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "main.py", line 51, in run
    await args.func(args)
  File "main.py", line 83, in do_download
    await download.download(args.session, args.gallery_url, download_timeout=args.download_timeout)
  File "/git/qnnnnez:e-downloader/download.py", line 122, in download
    await downloader.gallery.load_preview(downloader.session)
  File "/git/qnnnnez:e-downloader/gallery.py", line 67, in load_preview
    parts = doc.find('.//div[@class="gtb"]/p[@class="gpc"]').text.split(' ')
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by luckydonald** [comment]
Could that be because of the content warning?
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/2737108/96374870-c5a98880-1175-11eb-892a-f9e9e0e11fd2.png">

**Comment by luckydonald** [comment]
Apparently "View Gallery" appends `?nw=session` to the original url, and "Never Warn Me Again" adds `?nw=always`.

**Comment by luckydonald** [comment]
This in turn sets a cookie `nw` with the value `1` on either the whole page (`/`) or the current page as path, (here `/g/998495/13bba610b4`)

**Comment by luckydonald** [comment]
Following that logic 
```bash
echo 'Set-Cookie: nw=1; Domain=e-hentai.org; Path=/' | python main.py cookie-update
```
should be a workaround.

**Comment by luckydonald** [comment]
That indeed solves that.

**Comment by qnnnnez** [comment]
Cool. Personally I use exhentai, never encountered this issue.
